name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: "*/5 * * * *"   # roda a cada 5 minutos
  workflow_dispatch: {}  

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (clean)
        run: npm ci

      - name: Run tests (Mocha)
        env:
          JWT_SECRET: segredo-ci
        run: npm test
